### ISSUE TITLE
The first character in the Fasta file is not ">”.

### ISSUE THREAD

**Issue by Kinggerm** [chanzuckerberg/shasta#78] opened 2019-11-21 22:16 UTC
Dear shasta developers,
I am using shasta to assemble my nanopore fastq format data in linux server. But shasta v0.3.0 binary version (https://github.com/chanzuckerberg/shasta/releases/download/0.3.0/shasta-Linux-0.3.0) could not recognize my fastq file, but took it as fasta file and report error `The first character in the Fasta file is not ">".`
Do you have any ideas what I should do? 
Thanks in advance!
Jianjun

**Comment by paoloczi** [comment] 2019-11-21 22:22
Support for fastq files is in the latest code on GitHub, but not on release 0.3.0. To get it you have three choices:

- Download a test build (directions [here](https://chanzuckerberg.github.io/shasta/BuildingFromSource.html#DownloadTestBuild)).
- Build it yourself (directions [here](https://chanzuckerberg.github.io/shasta/BuildingFromSource.html)).
- Wait for release 0.4.0.

If none of these works for you please let me know and I can help.

**Comment by Kinggerm** [comment] 2019-11-24 21:41
Thank you! I used the test build, but got another issue:

    Shasta unreleased test build newer than release 0.3.0 at commit 380333c3b022af65f178e927786c58cf11b957f1
    2019-Nov-23 19:58:14.318097 
    This is the static executable for the Shasta assembler. It has no dependencies and requires no installation.
    
    Default values of assembly parameters are optimized for an assembly at coverage 60x. If your data have significantly different coverage, some changes in assembly parameters may be necessary to get good results.
    
    For more information about the Shasta assembler, see
    https://github.com/chanzuckerberg/shasta
    
    Complete documentation for the latest version of Shasta is available here:
    https://chanzuckerberg.github.io/shasta
    
    Options in use:
    Input files: S3_1_2-OND00358-1.F.fastq S3_1_2-OND00358-1.P.fastq S3_1_2-OND00358-2.F.fastq S3_1_2-OND00358-2.P.fastq S3_1_2-OND00362-1.F.fastq S3_1_2-OND00362-1.P.fastq S3_1_2-OND00362-2.F.fastq S3_1_2-OND00362-2.P.fastq 
    assemblyDirectory = Liuliu-shasta-test
    memoryMode = anonymous
    memoryBacking = 4K
    threadCount = 24
    
    useGpu = False
    
    [Reads]
    minReadLength = 2000
    palindromicReads.maxSkip = 100
    palindromicReads.maxDrift = 100
    palindromicReads.maxMarkerFrequency = 10
    palindromicReads.alignedFractionThreshold = 0.1
    palindromicReads.nearDiagonalFractionThreshold = 0.1
    palindromicReads.deltaThreshold = 100
    
    [Kmers]
    k = 10
    probability = 0.1
    suppressHighFrequencyMarkers = False
    enrichmentThreshold = 10
    
    [MinHash]
    version = 0
    m = 4
    hashFraction = 0.01
    minHashIterationCount = 10
    minBucketSize = 0
    maxBucketSize = 10
    minFrequency = 2
    allPairs = False
    
    [Align]
    alignMethodForReadGraph = 0
    alignMethodForMarkerGraph = 0
    maxSkip = 30
    maxDrift = 30
    maxTrim = 30
    maxMarkerFrequency = 10
    minAlignedMarkerCount = 100
    minAlignedFraction = 0
    matchScore = 3
    mismatchScore = -1
    gapScore = -3
    
    [ReadGraph]
    creationMethod = 0
    maxAlignmentCount = 6
    minComponentSize = 100
    maxChimericReadDistance = 2
    crossStrandMaxDistance = 6
    offsetTolerance0 = 100
    offsetTolerance1 = 0.1
    
    [MarkerGraph]
    minCoverage = 10
    maxCoverage = 100
    lowCoverageThreshold = 0
    highCoverageThreshold = 256
    maxDistance = 30
    edgeMarkerSkipThreshold = 100
    pruneIterationCount = 6
    simplifyMaxLength = 10,100,1000
    
    [Assembly]
    strategy = 0
    crossEdgeCoverageThreshold = 3
    markerGraphEdgeLengthThresholdForConsensus = 1000
    consensusCaller = Bayesian:guppy-2.3.5-a
    useMarginPhase = False
    storeCoverageData = False
    storeCoverageDataCsvLengthThreshold = 0
    
    [Phasing]
    phasingSimilarityThreshold = 0.5
    maxNeighborCount = 6
    
    This run uses options "--memoryBacking 4K --memoryMode anonymous".
    This could result in performance degradation.
    For full performance, use "--memoryBacking 2M --memoryMode filesystem"
    (root privilege via sudo required).
    Therefore the results of this run should not be used
    for benchmarking purposes.
    This assembly will use 24 threads.
    Setting up consensus caller Bayesian:guppy-2.3.5-a
    Using predefined Bayesian consensus caller guppy-2.3.5-a
    Bayesian consensus caller configuration name is Human guppy 2.3.5 chr1,chr2,chr3 GM24385 with hg38 priors and 1 pseudocounts 7-23-2019
    2019-Nov-23 19:58:14.333086 Begin loading reads from 8 files.
    2019-Nov-23 19:58:14.333187 Loading reads from /rigel/dsi/users/jj3111/Documents/2019-11-15-Liuliu-shasta/S3_1_2-OND00358-1.F.fastq
    /cm/local/apps/slurm/var/spool/job16690758/slurm_script: line 12: 14262 Bus error               shasta --Reads.minReadLength 2000 --threads 24 --assemblyDirectory Liuliu-shasta-test --input *fastq
    slurmstepd: error: Step 16690758.4294967294 hit memory limit at least once during execution. This may or may not result in some failure.

**Comment by paoloczi** [comment] 2019-11-24 22:10
This error message is not issued by Shasta, but by your Slurm system. It is possible that the Slurm system is monitoring memory usage by Shasta and that Shasta exceeded some memory usage limit enforced by Slurm. 

I am not familiar with Slurm, but perhaps somebody in your IT department can help you figure out what is going on. It is likely that to run this assembly Shasta needs more memory than is available on your system. This is happening at the very beginning of your assembly while Shasta just started loading the first of your 8 fastq files.

**Comment by paoloczi** [comment] 2019-12-10 21:44
Since there were no additional comments, I am closing this. Feel free to reopen it if you think the problem is caused by Shasta and is not simply a lack of sufficient memory. Please open another issue if you still have problems running your assembly.

**Closed by paoloczi** 2019-12-10 21:44 UTC
Labels: question
