### ISSUE TITLE
Threads option not available in 0.1.0 release?

### ISSUE THREAD

**Issue by reiverjohn** [chanzuckerberg/shasta#43] opened 2019-08-08 19:10 UTC
I note that the --threads option is mentioned in the documentation, but the prebuild binary release 0.1.0 does not seem to recognize this as a command option.  This is a problem for us, as we use shared compute resources, and the program appears to look at the total number of cores available and uses all of them.

**Comment by paoloczi** [comment] 2019-08-08 19:16
This is a duplicate of issue #42, fixed a few days ago. The `--threads` option will be available in the next release, or if you build the code yourself using the latest code on GitHub. 

If you prefer not to build the code yourself, see the resolution of issue #42 for a temporary link to a Linux executable that includes this option, but keep in mint that this executable is not as stable as you would expect from a released version. In addition, some of the options are different from release 0.1.0.

**Comment by paoloczi** [comment] 2019-08-08 19:19
The reason the `--threads` option is mentioned in the documentation is that the documentation always refers to the latest code available on GitHub, not to the latest release. Documentation for a given release can be obtained by downloading the tar file for that release, or locally via `git checkout`.

**Closed** 2019-08-08 19:19 UTC
Labels: duplicate, enhancement
