### ISSUE TITLE
.csv visualization

### ISSUE THREAD

**Issue by RasmusBuntzen** [chanzuckerberg/shasta#285] opened 2022-04-04 13:59 UTC
Hi,
I'm trying to tweak some of the configurations for my Shasta run. For this I want to see some of the plots created by my less successful runs, especially LowHashBucketHistogram.csv
I however haven't been able to get any meaningful plots out of the csv files. 
Any general help of how to visualize the csv files would be greatly appreciated.

Thanks in advance,
Rasmus

**Comment by paoloczi** [comment] 2022-04-04 14:26
To understand bucket population in an assembly I use `LowHashBucketHistogram.csv` to do a scatter plot of `FeatureCount` (vertical axis) versus `BucketSize` (horizontal axis). This needs to be a scatter plot without lines. Then I adjust the horizontal scale, usually to a maximum of 50 or 100 depending on coverage, and I also do some manual adjustments of the vertical scale. The result is something like this:

![image](https://user-images.githubusercontent.com/25391437/161563980-31c02aa9-491c-49c1-a8ff-1748e6ffb62a.png)

This was done on LibreOffice Calc, but you could just as well do it in Excel or using Gnuplot.

The peak near zero shows low population buckets due to errors. The main peak (around 40 in this case) shows the "healthy" buckets. Their population is determined by coverage, with some loss due to errors. The buckets with extremely high population, excluded from the plot, are caused by repeats.

You want to make sure that `--MinHash.minBucketSize` and `--MinHash.maxBucketSize` bracket the body of the main peak. The figure above suggests something like `--MinHash.minBucketSize 20 --MinHash.maxBucketSize 60`.

Also, always feel free to post Shasta related questions here, particularly if you are unable to optimize assembly results to your satisfaction.

**Comment by paoloczi** [comment] 2022-04-15 21:13
I am closing this due to lack of additional discussion.

**Closed by paoloczi** 2022-04-15 21:13 UTC
Labels: question
